name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]
  pull_request_target:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'  # Don't fail the job on vulnerabilities
        continue-on-error: true
          
      - name: Ensure SARIF file exists
        run: |
          if [ ! -f "trivy-results.sarif" ]; then
            echo "Creating minimal SARIF file since Trivy didn't generate one"
            cat > trivy-results.sarif << 'EOF'
          {
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "Trivy",
                    "informationUri": "https://github.com/aquasecurity/trivy",
                    "version": "0.0.0"
                  }
                },
                "results": []
              }
            ]
          }
          EOF
          fi
          
      - name: Check SARIF file
        id: check-sarif
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "sarif-exists=true" >> $GITHUB_OUTPUT
            FILE_SIZE=$(stat -c%s trivy-results.sarif 2>/dev/null || stat -f%z trivy-results.sarif)
            echo "SARIF file found, size: $FILE_SIZE bytes"
            echo "SARIF content preview:"
            head -5 trivy-results.sarif
          else
            echo "sarif-exists=false" >> $GITHUB_OUTPUT
            echo "No SARIF file found"
          fi
          
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: steps.check-sarif.outputs.sarif-exists == 'true'
        with:
          sarif_file: 'trivy-results.sarif'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Run security audit
        run: npm audit --audit-level=high

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check code formatting
        run: |
          # Check if files are properly formatted
          npx prettier --check "**/*.{js,json,md}" || {
            echo "Code formatting issues found. Run 'npx prettier --write .' to fix."
            exit 1
          }

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: test-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Test Docker image
        run: |
          docker run --rm test-image:latest --version

  size-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check package size
        run: |
          echo "📦 Package Analysis"
          echo "==================="
          
          # Check npm package size
          NPM_SIZE=$(npm pack --dry-run 2>/dev/null | grep -E 'package size' | awk '{print $3 $4}' || echo "unknown")
          echo "📊 NPM Package Size: $NPM_SIZE"
          
          # Check total project size
          TOTAL_SIZE=$(du -sh . 2>/dev/null | awk '{print $1}' || echo "unknown")
          echo "📁 Total Project Size: $TOTAL_SIZE"
          
          # Check key directories
          echo "📂 Directory Breakdown:"
          du -sh templates/ scripts/ .github/ 2>/dev/null || echo "Unable to calculate directory sizes"
          
          # List largest files
          echo "📄 Largest Files:"
          find . -type f -not -path './node_modules/*' -not -path './.git/*' -exec ls -lh {} \; | sort -k5 -hr | head -10 | awk '{print $5 " " $9}' || echo "Unable to list files"

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          allow-licenses: MIT, ISC, Apache-2.0, BSD-2-Clause, BSD-3-Clause

  pr-summary:
    runs-on: ubuntu-latest
    needs: [security-check, test, lint-and-format, docker-build, size-check]
    if: always()
    steps:
      - name: PR Summary
        uses: actions/github-script@v7
        with:
          script: |
            const jobs = [
              { name: 'Security Check', status: '${{ needs.security-check.result }}' },
              { name: 'Tests', status: '${{ needs.test.result }}' },
              { name: 'Lint & Format', status: '${{ needs.lint-and-format.result }}' },
              { name: 'Docker Build', status: '${{ needs.docker-build.result }}' },
              { name: 'Size Check', status: '${{ needs.size-check.result }}' }
            ];
            
            const passed = jobs.filter(job => job.status === 'success').length;
            const total = jobs.length;
            
            const summary = `## PR Check Results 📊\n\n` +
              `**${passed}/${total} checks passed**\n\n` +
              jobs.map(job => {
                const icon = job.status === 'success' ? '✅' : 
                           job.status === 'failure' ? '❌' : '⏸️';
                return `${icon} ${job.name}`;
              }).join('\n');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
